version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - ./gradlew build -x test

artifacts:
  files:
    - ./build/libs/helloworld-0.0.1-SNAPSHOT.jar
  name: helloworld-0.0.1-SNAPSHOT.jar